mysql:
  addr: "1.117.141.66:3306"
  username: "root"
  password: "lgp123456"
  maxConn: 10
  maxOpen: 100
  db: "img"
redis:
  addr: "1.117.141.66:6379"
  password: "123456abc"
  db: 0
  poolSize: 50
system:
  host: "0.0.0.0"
  port: "8080"
  env: "pro"
token:
  signingKey: "e199ad17-c090-43cb-b095-1dc55c209a77"
  expiresTime: 604800
logger:
  filename: "log/system/log.txt"
  maxSize: 1
  maxBackups: 5
  maxAge: 30
  compress: false
  showLine: true
  level: "debug"

gin:
  mode: release
  logger:
    filename: "log/gin/log"
    maxSize: 1
    maxBackups: 5
    maxAge: 30
    compress: false
    showLine: true
    level: "debug"