mysql:
  addr: "1.117.141.66:3306"
  username: "root"
  password: "lgp123456"
  maxConn: 200
  maxOpen: 100
  db: "img"
redis:
  addr: "1.117.141.66:6379"
  password: "123456abc"
  db: 0
  poolSize: 50
system:
  host: "0.0.0.0"
  port: 8080
  env: "dev"
token:
  signingKey: "e199ad17-c090-43cb-b095-1dc55c209a77"
  expiresTime: "7d"
logger:
  filename: "log/log.txt"
  maxSize: 1
  maxBackups: 5
  maxAge: 30
  compress: false
  showLine: true
  prefix: "lgp"
  level: "debug"